### ISSUE TITLE
Code not testable with Travis CI in current form.

### ISSUE THREAD

**Issue by kward** [hypebeast/go-osc#18]
Please consider restructuring the codebase to make it work. See my forked repository for what was necessary. The changes are quite simple.
https://github.com/kward/go-osc

FYI, I'd love to deprecate my repository back in favor of yours.

Tks for the awesome library! Was able to get it working in both directions with TouchOSC in a matter of hours.

**Comment by hypebeast** [comment]
Hi KWard. Thanks for your changes and effort. Just open a pull request and I'll be happy to merge it.

Thanks,
//Sebastian
