### ISSUE TITLE
Can't build shuttle-go 

### ISSUE THREAD

**Issue by faridosc** [hypebeast/go-osc#36]
Hi, after this commit https://github.com/hypebeast/go-osc/commit/edff003c8de14fd0897d4c881c1683b88b01729f I am unable to build shuttle-go https://github.com/abourget/shuttle-go, is there a way to revert it or could you provide a fix/workaround? 

thanks

**Comment by hypebeast** [comment]
Could you provide some more details for the error, please?

**Comment by hypebeast** [comment]
My guess is that the build breaks, because it was a breaking change. What you can do is to checkout a working version of go-osc to the vendor folder in the project.

**Comment by faridosc** [comment]
go get -v github.com/abourget/shuttle-go gives this:

```
github.com/abourget/shuttle-go (download)
created GOPATH=/home/farid/go; see 'go help gopath'
github.com/hypebeast/go-osc (download)
github.com/hypebeast/go-osc/osc
github.com/abourget/shuttle-go
# github.com/abourget/shuttle-go
go/src/github.com/abourget/shuttle-go/osc.go:13:8: server.Handle undefined (type *osc.Server has no field or method Handle)
```

**Comment by faridosc** [comment]
> What you can do is to checkout a working version of go-osc to the vendor folder in the project.

How to do that?

**Comment by glynternet** [comment]
Hi @faridosc,

I've updated your shuttle-go project for you to match the latest version of this repository: https://github.com/abourget/shuttle-go/pull/5

I have left a note about Go modules on the pull request, as that the standard way to do dependency management in the Go community.

**Comment by hypebeast** [comment]
Yes, @glynternet is totally right. His PR is the way to go and the project shuttle-go should think about to use Go modules in the feature.

My proposal was a quick fix without the need to change the shuttle-go project and what you can do locally on your own machine without the need for a PR.

The basic idea is the following:

- Checkout go-shuttle on your dev machine
- and then checkout the correct version of go-osc in the vendor folder

then you should be able to build go-shuttle. But this is really just a workaround.

**Comment by faridosc** [comment]
Thanks folks for the help. Unfortunately the projects seems abandoned...

**Comment by glynternet** [comment]
The PR over at https://github.com/abourget/shuttle-go/pull/5 was merged, so you should be good to go @faridosc

**Comment by faridosc** [comment]
Thanks folks
