### ISSUE TITLE
Close crashes if server is not running

### ISSUE THREAD

**Issue by briansorahan** [hypebeast/go-osc#4]
Found this due to stupid behavior on my part, but thought it might be good to be more defensive in the OscServer.Close method. Here is the code that reproduces:

```go
package main

import (
	"github.com/hypebeast/go-osc/osc"
)

func main() {
	server := osc.NewOscServer("127.0.0.1", 23898)
	server.Close()
}
```

**Comment by hypebeast** [comment]
This issue is fixed with #5
