### ISSUE TITLE
Stuttering type names

### ISSUE THREAD

**Issue by kisielk** [hypebeast/go-osc#9]
It would be nice if the types in the package could be renamed, since they all currently start with `Osc`, but the library is already named `osc` so the code ends up being filled with `osc.Osc`. It would be nicer to just be able to write `osc.Server` or `osc.Client`.

See also http://blog.golang.org/package-names (particularly the Naming Package Contents section)

**Comment by hypebeast** [comment]
Thanks for the hint. I'll take a look at it when i have time (today or tomorrow evening).
